/* Public campaign pages. Existing content generators remain the source of truth. */
const fs = require('fs');
const path = require('path');
const facts = require('../data/product-facts');
const root = path.resolve(__dirname, '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const write = (p, s) => { fs.mkdirSync(path.dirname(path.join(root,p)), {recursive:true}); fs.writeFileSync(path.join(root,p), s); };
const escape = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const visual = (kind, label) => `<div class="product-visual visual-${kind}" role="img" aria-label="${label}"></div>`;
const stores = () => `<div class="store-links"><a href="${facts.appStoreUrl}" data-analytics-event="app_store_click" data-platform-target="ios" aria-label="Download Flowtime on the App Store"><img src="https://developer.apple.com/assets/elements/badges/download-on-the-app-store.svg" alt="Download on the App Store" width="150" height="50"></a><a href="${facts.googlePlayUrl}" data-analytics-event="play_store_click" data-platform-target="android" aria-label="Get Flowtime on Google Play"><img class="google-badge" src="https://play.google.com/intl/en_us/badges/static/images/badges/en_badge_web_generic.png" alt="Get it on Google Play" width="169" height="65"></a></div>`;
const chapter = (n,title,body,kind,theme='',reverse=false,id='') => `<section ${id ? `id="${id}"` : ''} class="campaign-chapter ${theme} ${reverse?'reverse':''}"><div class="chapter-inner"><div class="chapter-copy"><span class="chapter-number">${n}</span><h2>${title}</h2>${body}</div><div class="chapter-art">${visual(kind,({white:'Flowtime light theme with a large running timer',modes:'Pomodoro, Classic, Flowmodoro and Custom timer screens',awareness:'Pink Flowtime timer with a gentle time awareness reminder',shield:'Focus mode with distracting apps blocked and an Override control',reports:'Flowtime Projects, History and Reports screens',achievements:'Discovered Flowtime achievement cards'})[kind])}</div></div></section>`;
const pricing = `<section id="pricing" class="campaign-pricing"><div class="section-intro"><span class="chapter-number">07</span><h2>Free or Pro.<br>You decide.</h2><p>Start for free. Upgrade when you need more.</p></div><div class="plans"><article class="plan"><span class="meta">THE ESSENTIALS</span><h3>Free</h3><p class="plan-price">$0 <span>forever</span></p><ul><li>Standard timer</li><li>Basic notifications</li><li>Pomodoro with fixed intervals</li><li>1 project</li><li>1 day of history</li></ul><a class="pill" href="/download/">Get started <span>↗</span></a></article><article class="plan plan-pro"><span class="meta">A LITTLE MORE POSSIBILITY</span><h3>Pro</h3><p class="plan-price">$3.99 <span>/ month</span></p><p class="plan-options">$24.99 / year · $49.99 lifetime</p><ul><li>Flow Sessions &amp; Flowmodoro</li><li>Custom Pomodoro intervals</li><li>Unlimited projects &amp; history</li><li>App Shielding</li><li>Quick Start Templates &amp; Reminder Profiles</li><li>Accent colors, reports &amp; exports</li><li>All future Pro features</li></ul><a class="pill" href="/download/">Find your flow <span>↗</span></a></article></div><p class="pricing-note">Prices shown in USD. Local pricing is available in your app store.</p></section>`;
const final = `<section id="download" class="campaign-final"><span class="meta">YOUR TIME. YOUR WAY.</span><h2>Ready when<br>you are.</h2>${stores()}<p>No account. No cloud. Just focus.</p><a class="text-link" href="/updates/">Follow the build →</a></section>`;
const source = read('index.html');
// Keep the original metadata, security policy, analytics and structured data.
const head = source.slice(0, source.indexOf('<body')).replace(/(src|href)="(scripts|data|assets)\//g, '$1="/$2/').replace(/<link rel="preload" as="image"[^>]*>/, '<link rel="preload" as="image" href="/assets/flowtime-campaign-desktop.png" fetchpriority="high" />');
const oldFaq = source.match(/<section[^>]*id="faq"[\s\S]*?<\/section>/)?.[0] || '';
const faqPath = 'data/support-faq.html';
if (oldFaq && !fs.existsSync(path.join(root,faqPath))) write(faqPath,oldFaq);
const faq = fs.existsSync(path.join(root,faqPath)) ? read(faqPath) : oldFaq;
function shell(content) {return `<body id="top" class="campaign-site"><div id="site-header"></div><main id="main-content">${content}</main><div id="site-footer"></div><script>window.flowtimeRoot='/';window.flowtimePreserveTitle=true;window.renderSection=function(id,html){var el=document.getElementById(id);if(el)el.outerHTML=html;};</script><script src="/scripts/i18n.js"></script><script src="/sections/header.js"></script><script src="/sections/footer.js"></script><script src="/scripts/design.js"></script></body></html>`;}
function page(route,title,description,content) {let h=head.replace(/<title>[\s\S]*?<\/title>/,`<title>${escape(title)} — Flowtime</title>`).replace(/href="style.css[^" ]*"/, 'href="/style.css"').replace(/href="assets\//g,'href="/assets/').replace(/<meta name="description"\s+content="[^"]*"/,`<meta name="description" content="${escape(description)}"`).replace(/<link rel="canonical" href="[^"]*"/,`<link rel="canonical" href="${facts.siteUrl}/${route}/"`).replace(/<script type="application\/ld\+json"[\s\S]*?<\/script>/g,'');h=h.replace(/<meta property="og:title" content="[^"]*"/,`<meta property="og:title" content="${escape(title)} — Flowtime"`).replace(/<meta property="og:url" content="[^"]*"/,`<meta property="og:url" content="${facts.siteUrl}/${route}/"`);write(`${route}/index.html`,h+shell(content));}
const home = `<section class="campaign-hero"><div class="hero-copy"><h1>Focus,<br>your way.</h1><p class="hero-deck">A minimal focus timer for<br>a more intentional day.</p>${stores()}<p class="quiet">No account. No cloud. Just you and your time.</p></div><div class="hero-art">${visual('hero','Flowtime dark timer with oversized green digits on a colorful abstract background')}<span class="hero-mantra">FOCUS<br>TRACK<br>STAY AWARE<br>DO MORE</span></div></section>
${chapter('01','Just start.','<p class="chapter-deck">No setup.<br>No account.<br>No distractions.</p><p>Open Flowtime and start. Everything stays on your device, so you can focus on what matters.</p>','white','',true,'simplicity')}
${chapter('02','Focus<br>however<br>you want.','<p>Choose a mode that fits<br>your task and your day.</p><div class="mode-labels"><span>Pomodoro</span><span>Classic</span><span>Flowmodoro</span><span>Custom</span></div>','modes','chapter-dark',false,'focus-modes')}
${chapter('03','Stay aware<br>without<br>watching<br>the clock.','<p>Gentle reminders help you notice passing time, even during deep focus.</p>','awareness','chapter-pink',false,'time-awareness')}
${chapter('04','Keep<br>distractions out.','<p>App Shielding helps you stay focused by blocking distracting apps.</p><p>You’re always in control. Override when you need to, before you get pulled away.</p>','shield','',true,'app-blocking')}
${chapter('05','See where<br>your time went.','<p>Projects, history and reports help you understand your focus and build better habits.</p>','reports','chapter-dark',false,'reports')}
${chapter('06','Discover<br>achievements.','<p>Celebrate your progress with hidden achievements.<br>No streaks. No pressure.<br>Just small milestones.</p>','achievements','','', 'achievements')}
<section class="campaign-review"><span class="meta">FROM THE APP STORE</span><blockquote>“This beautiful well designed app from an indie dev… Totally worth it in my opinion.”</blockquote><p aria-label="5 out of 5 stars">★★★★★</p><p class="quiet">Mrs.changhua · App Store review</p></section>${pricing}<section class="campaign-learn"><span class="meta">A DIFFERENT PERSPECTIVE</span><h2>Work with time.<br>Not against it.</h2><p>Ideas for finding focus, noticing time, and making room for what matters.</p><a class="pill" href="/learn/">Explore Learn ↗</a><a class="text-link" href="/support/">Questions? Support &amp; FAQ →</a></section>${final}`;
write('index.html',head+shell(home.replace('<section class="campaign-learn">', '<section id="faq" class="campaign-learn compact-faq"><h2>What is Flowtime?</h2><p>Flowtime is a flexible focus timer and personal time tracker for iPhone and Android. No account is required.</p><a class="text-link" href="/support/">Explore all questions &amp; answers →</a></section><section class="campaign-learn">')));
page('pricing','Free or Pro. You decide.','Explore Flowtime Free and Pro. Flexible focus with monthly, yearly and lifetime options.',pricing+final);
page('download','Get Flowtime','Download Flowtime for iOS and Android. No account required.',`<section class="download-page"><div><span class="meta">IOS &amp; ANDROID</span><h1>Get Flowtime.</h1><p>A little more focus.<br>A little more room for you.</p>${stores()}<p class="quiet">No account. No cloud. Just you and your time.</p></div><div class="download-art">${visual('white','Flowtime minimal white timer')}${visual('hero','Flowtime colorful dark timer')}</div></section>`);
page('support','Support & FAQ','Answers to your questions about Flowtime timers, privacy, platforms and Pro.',`<section class="editorial-hero"><span class="meta">HERE TO HELP</span><h1>Support &amp; FAQ</h1><p>A little guidance. Then back to your day.</p></section><div class="support-layout"><aside><a href="#faq">Using Flowtime ↗</a><a href="${facts.supportUrl}">Contact support ↗</a><a href="${facts.privacyPolicyUrl}">Privacy ↗</a><a href="${facts.termsUrl}">Terms ↗</a></aside><div>${faq}</div></div>`);
const posts=[];
for(const category of ['guides','comparison'])for(const file of fs.readdirSync(path.join(root,'content',category))){if(!file.endsWith('.md'))continue;const text=read(`content/${category}/${file}`);const fm=text.match(/^---\r?\n([\s\S]*?)\r?\n---/)?.[1]||'';const data={};fm.split(/\r?\n/).forEach(l=>{const i=l.indexOf(':');if(i>0)data[l.slice(0,i)]=l.slice(i+1).trim().replace(/^"|"$/g,'');});const topic=/adhd|neurodivergent/i.test(data.title)?'ADHD':/account|removed/i.test(data.title)?'Behind the App':/time blindness|reminder|awareness|four hours/i.test(data.title)?'Time Awareness':category==='comparison'?'Focus':'Guides';posts.push({title:data.title||file,description:data.description||'',url:`/${category}/${file.replace(/\.md$/,'')}/`,topic,minutes:Math.max(1,Math.ceil(text.split(/\s+/).length/220))});}
posts.sort((a,b)=>(b.url.includes('why-pomodoro')?1:0)-(a.url.includes('why-pomodoro')?1:0));
const cards=posts.map((p,i)=>`<a class="learn-entry ${i===0?'learn-featured':''}" data-topic="${p.topic}" href="${p.url}">${i===0?`<div class="learn-art">${visual('modes','Four different ways to focus in Flowtime')}</div>`:''}<div class="learn-copy"><span class="meta">${p.topic} · ${p.minutes} MIN READ</span><h2>${escape(p.title)}</h2><p>${escape(p.description)}</p><span class="entry-arrow" aria-hidden="true">↗</span></div></a>`).join('');
page('learn','Learn to work with time','Articles, practical guides and stories about focus, productivity and Flowtime.',`<section class="editorial-hero"><span class="meta">IDEAS FOR A MORE INTENTIONAL DAY</span><h1>Learn to<br>work with time.</h1><p>Articles, guides and stories about focus,<br>productivity and the way we spend our days.</p><a class="text-link" href="/updates/">Behind the app: follow the build →</a></section><section class="learn-list"><div class="learn-filters" role="group" aria-label="Filter articles">${['All','Focus','Guides','ADHD','Time Awareness','Behind the App'].map(t=>`<button type="button" data-learn-filter="${t}" aria-pressed="${t==='All'}">${t}</button>`).join('')}</div><p class="sr-only" data-learn-count aria-live="polite"></p><div class="learn-grid">${cards}</div></section>`);
console.log('Built campaign home, Learn, pricing, download and support pages.');
